version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nft-rankings"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-he1scb7etu0i"
s3_prefix = "nft-rankings"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
